### ISSUE TITLE
Cannot decoding fax4-encoded tiff; decoding stops partway through file

### ISSUE THREAD

**Issue by stephenjudkins** [pdf-rs/fax#6]
See attachment: [fax4.tiff.zip](https://github.com/pdf-rs/fax/files/14859602/fax4.tiff.zip)

Expected: ![image](https://github.com/pdf-rs/fax/assets/8593/5c8191e2-9dc5-44bb-b67e-2bc4ed34f559)
Actual: ![image](https://github.com/pdf-rs/fax/assets/8593/9c7d731d-dd9e-455c-b0ba-bebae04a4ded)

`decode_g4` stops hitting the callback after line 408.

It looks like line 407 is not being decoded properly.

**Comment by stephenjudkins** [comment]
This is on the latest `master` (https://github.com/pdf-rs/fax/commit/54f0a331a5cc9aa517fc05e462e1261ada779fe1)

**Comment by s3bk** [comment]
Thanks, I have added it to my test set and will try to investigate it soon.

**Comment by stephenjudkins** [comment]
Appreciate it! Thank you

**Comment by s3bk** [comment]
Appears to be fixed.

**Comment by stephenjudkins** [comment]
Indeed it does. Thanks so much for the fix!
