### ISSUE TITLE
Tiff - CCITT Encoding

### ISSUE THREAD

**Issue by inzanez** [pdf-rs/fax#8]
Hi

I am trying to encode a TIF to CCITT Group 4. I already modified my TIFs in a way that they have been dithered and binarized to get a better quality and already ensure that there are only `0` or `255` color values present.

The encoder seems pretty straight forward,...except that I am not sure if `pels` is the right way to go here or if the custom iterator would be the way to go.

The other part I am not yet quite sure: the `tiff::wrap` function. Is that somehow a generic that should work for every image or is that more like a sample (I think the latter is the case here),...?

I currently do not get output that is valid :-) 

```
use fax::encoder::Encoder;
use fax::{tiff, VecWriter};
use fax::decoder::pels;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let data = std::fs::read("path/to/some.tiff")?;
    let img = image::load_from_memory(&data)?.into_luma8();

    let w = VecWriter::new();
    let mut encoder = Encoder::new(w);

    for r in img.rows(){
        let len = r.len() as u16;
     //   encoder.encode_line(r.into_iter().map(|l| match l.0[0] { 255 => fax::Color::Black, _ => fax::Color::White}), len);
        encoder.encode_line(pels(&r.into_iter().map(|l| l.0[0] as u16).collect::<Vec<u16>>(), len), len);
    }

    let res =  encoder.finish().finish();

    let encoded = tiff::wrap(&res, img.width(), img.height());
    std::fs::write("/tmp/test.tif", encoded)?;

    Ok(())
}
```

**Comment by s3bk** [comment]
No, `pels` is part of the decoder. the line you commented out is correct (except 0 should be black I think).
the wrap call looks correct too.

**Comment by s3bk** [comment]
Dithering is a valid technique for B/W images, but the fax encoding may not give you good compression ratios.
It is a fairly simple encoding that doesn't much memory or cpu power and that old fax machines could run on the fly.

Modern image compression is far better.

**Comment by s3bk** [comment]
The encoder looks to be broken too.

**Comment by inzanez** [comment]
Ok,...I thought it must be broken as the output is not really valid. And yes, I agree, there are far better compression formats, but I need CCITT Group4 for compatibility reasons. I wish I wouldn't,...;-)

**Comment by inzanez** [comment]
Well, I am not really impressed by the documentation of the CCITT Group 4 compression,...I guess I will refer to using an external process / library that does the conversion.

**Comment by s3bk** [comment]
I am trying to debug the encoder. Which isn't so easy because there are multiple valid encodings and some encoders don't follow the specification.
My current approach is to encode and decode again and see which line gets incorrectly decoded and then look at the encoding of that line.

**Comment by s3bk** [comment]
I have used wasmtime to sandbox untrusted C code for image decompression. Unfortunately it requires quite a lot of glue.
I will try to fix the encoding.

**Comment by inzanez** [comment]
Ok. Well, I appreciate that! It seems like an interesting format, but again, the official documentation is really...not that great. It seems a bit chaotic to me.

**Comment by s3bk** [comment]
If you'd like I can try and help you figuring out a different solution that doesn't require CCITT images. Ping me on zulip if you are interested.

**Comment by inzanez** [comment]
That is very kind of you, but I do not have any means of controlling the format that is to be delivered. It must be CCITT Group 4,...no way around that, as the destination system only accepts that image type for now.

**Comment by s3bk** [comment]
[T-REC-T.6-198811-I!!PDF-E.pdf](https://github.com/pdf-rs/fax/files/14896090/T-REC-T.6-198811-I.PDF-E.pdf)
There is an uncompressed mode that you could use if the device supports it.

**Comment by s3bk** [comment]
But yea, use TIFFInitCCITTFax4 from libtiff for now, until I get this fixed.

**Comment by s3bk** [comment]
It is fixed!

**Comment by inzanez** [comment]
Hm, could it be that some commit is missing? Not sure,...just because I only see commits on the README and Cargo.toml. Maybe I missed something.

**Comment by s3bk** [comment]
I may have forgotten to push it.

**Comment by inzanez** [comment]
@s3bk very nice! I will definitely check that out tonight. Thank you very much!
